### ISSUE TITLE
InvalidStateError when cancelling

### ISSUE THREAD

**Issue by vdwees** [gawel/aiocron#19]
When I cancel an asyncio.Task that is awaiting an aiocron next(), sometimes I see this error. Any ideas?
```
ERROR:asyncio:Exception in callback <bound method Cron.set_result of <Cron * * * * * */2 <function null_callback at 0x7f23a49f2700>>>
handle: <Handle Cron.set_result>
Traceback (most recent call last):
  File "uvloop/cbhandles.pyx", line 63, in uvloop.loop.Handle._run
  File "venv/lib/python3.9/site-packages/aiocron/__init__.py", line 97, in set_result
    self.future.set_result(result)
asyncio.exceptions.InvalidStateError: invalid state
```

**Comment by gawel** [comment]
Definitely a bug. I guess `self.future` is canceled when we try to set it. Do you have a snippet to reproduce the problem ?

**Comment by vdwees** [comment]
Its not every time, but on my machine if I run this a few times it does show up. 

```python

import asyncio
from datetime import timezone

import aiocron


async def wait_for():
    try:
        await aiocron.crontab("* * * * * */1", tz=timezone.utc).next()
    except asyncio.CancelledError:
        print("cancelled")
    else:
        print("done")


async def main():
    task = asyncio.create_task(wait_for())
    await asyncio.sleep(0.5)
    for _ in range(100000):
        if not task.cancelled():
            task.cancel()
        await asyncio.sleep(0)
    await task

asyncio.run(main())
```

**Comment by vdwees** [comment]
I've added an explicit call to stop() on receiving the cancelled error, which seems like a reasonable workaround.
